### ISSUE TITLE
is this library compatible with client side blazor projects?

### ISSUE THREAD

**Issue by soomon** [Postlagerkarte/blazor-dragdrop#1]
Hi,

I tried adding the package to my client project, but the using statement in Services.cs is not recognized:

Error	CS1061	'IServiceCollection' does not contain a definition for 'AddBlazorDragDrop' and no accessible extension method 'AddBlazorDragDrop' accepting a first argument of type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)	ProjMan.Client	Startup.cs	25	Active

Error	CS0234	The type or namespace name 'DragDrop' does not exist in the namespace 'Blazor' (are you missing an assembly reference?)	ProjMan.Client	Startup.cs	15	Active

**Comment by Postlagerkarte** [comment]
Thanks for the report @soomon 

Please use update to version 1.0.8 -  it supports client side blazor projects.

**Comment by soomon** [comment]
thanks for the update!
I installed the package (in the clien tproject). The error is gone.
Also I have added the stylesheet to index.html in the client side project.

once I figured out that I need to add the namespace @using Blazor.DragDrop.Core all errors are gone. 
Will try to implement your example now. 

Thanks again!
