### ISSUE TITLE
AllowSwap doesn't work correctly with MaxItems

### ISSUE THREAD

**Issue by brentfurry** [Postlagerkarte/blazor-dragdrop#10]
Hello,

I have a dynamic list of components each with it's own dropzone.  Each dropzone will always have 2 items.  The following allows me to swap items from one dropzone to another, but does not work when trying to swap items within the same dropzone. 

**Edit
It also appears to lose the sort order.  

    <Dropzone Class="@GetCSSClasses()" AllowSwap="true" MaxItems="2">
        <DraggablePanel PagePanel="@SpreadPanel.LeftHandPagePanel" />
        <DraggablePanel PagePanel="@SpreadPanel.RightHandPagePanel" />
    </Dropzone>

**Comment by Postlagerkarte** [comment]
Hi @brentfurry  - thank you for reporting this bug.

It is fixed in v1.1.5

**Comment by brentfurry** [comment]
Awesome, Thanks!
