### ISSUE TITLE
How are you supposed to access properties of a draggable item?

### ISSUE THREAD

**Issue by devgibsonsp** [Postlagerkarte/blazor-dragdrop#11]
I am going to preface this and say that I am definitely not an expert in C#.

How are you supposed to access the public properties in DraggableItem.cs? I am looking to essentially create 2 draggable zones and keep track of the items and their order in one of the zones. I see some properties that look helpful (OrderPosition & OriginDropzoneId ) but there doesn't seem to be a way to actually access this data.

Additionally, I am getting console [TRACE] messages from this library that are spamming the console. Is there a way to disable this?

**Comment by Postlagerkarte** [comment]
Hi @devgibsonsp,

you can inject the DragDropService into your component and get the Draggables for a Dropzone.

```
<Dropzone Name="MyDropzone">

</Dropzone>

<button @onclick="Foo">Click Me</button>

@code {

    [Inject]
    public DragDropService DragDropService { get; set; }

    public void Foo()
    {
        var items = DragDropService.GetDraggablesForDropzone("MyDropzone");

    }

}
```
If you want to attach more infos to your Draggable you can use the .Tag property.

Does this help?

**Comment by devgibsonsp** [comment]
Hi @Postlagerkarte 

That worked great and was very simple. My apologies for adding this as an issue.
