### ISSUE TITLE
Is blazor-dragdrop really compatible with .NET 5.0 ?

### ISSUE THREAD

**Issue by sylvainonweb** [Postlagerkarte/blazor-dragdrop#113]
Hi, 

when I try to build my application on my build server, I encounter this error 
`error NU1202: Le package blazor-dragdrop 2.2.2 n'est pas compatible avec net50 (.NETFramework,Version=v5.0). Le package blazor-dragdrop 2.2.2 prend en charge�: netstandard2.1 (.NETStandard,Version=v2.1)`

It seems that blazor-dragdrop 2.2.2 is based on .NET Standard 2.1 which is not compatible with .NET 5.0.
Is it true ? If yes, could you create a version based on .NET 5.0 ?

**Comment by ViRuSTriNiTy** [comment]
The update of the project file for .NET 5.0 support is part of PR #107. Sadly the repo owner is not responding for weeks now and your only option right now is to fork the project and use it as a git submodule. This way you can change the project file in your fork.

**Comment by Postlagerkarte** [comment]
Sorry guys - I am simply overwhelmed with work - thus all the delays.
I have not yet worked on 107 but I have published a version 2.3.0 with full support for .NET 5.0
Should be available as nuget package in a few moments.
