### ISSUE TITLE
Question: Comfort with Server-Side?

### ISSUE THREAD

**Issue by JasonIrby** [Postlagerkarte/blazor-dragdrop#114]
My team is evaluating this library and appreciate all the work the contributors have put in.

The demo page is done as Blazor server, but our team is a little concerned about how that will work real-world with imperfect networks and more complex data.  Mainly concerned about how sensitive Drag-Drop user experience would be to the round trip to server to respond to events.  

Is there justification for concern there?  

Thanks again.
-Jason

**Comment by Postlagerkarte** [comment]
Yes, latency is expected when you have over-the network interactions and can lead to bad user experience. If you are talking enterprise/coorperate network you are probably fine, if you are talking Internet I share you concerns and would not use the server side approach. I assume using webassembly is not feasible?
