### ISSUE TITLE
Internal dictionary management

### ISSUE THREAD

**Issue by mattosaurus** [Postlagerkarte/blazor-dragdrop#12]
Hi,

This is a great library, it certainly makes drag and drop a lot easier to use.

I'm having some issues when navigating between pages with the internal dictionary being reuesed and so copying over items onto the new page.

I've created an example project here.

https://github.com/mattosaurus/CampaignCalendar

The aim is to be able to drag items from a standard list of events onto a calendar day and for that to then be persisted to a SQL database in the backend. When navigating to a new month I would then read in a list of events from the SQL database and use it to populate the dropzones with items.

The immediate issue I have is that when dragging an item onto a day and then navigating to the next month the item appears there as well which I believe is due to the reuse of the internal dictionary between pages (this is probably Blazor trying to be helpful).

Would it make sense to allow the internal dictionary to be set from the service so dropzones and items could be populated at initialization and it could be manually cleared and reset when navigating to a new page?

Let me know if you think this could be a useful feature and can see a way to implement it, I had a look at adding this functionality but couldn't get it to work though I'll continue investigating (thinking about it, a data store interface might be a good idea but that's probably quite a bit more work to implement).

**Comment by Postlagerkarte** [comment]
Hello @mattosaurus - thank you for contacting me.

For your specific use case I suggest you try to create 12 seperate dropzones in your day component and toggle visiblity of them depending on the displayed month. 

```
        <div class="card-body">
            <h6 class="card-title" id="@int.Parse(DayDateTime.ToString("yyyyMMdd"))">@DayDateTime.Day</h6>

            <div class="@(Month.MonthStartDateTime.Month == 1 ? "visible" : "invisible")">
                <Dropzone class="card-dropzone w-100">
                </Dropzone>
            </div>

            <div class="@(Month.MonthStartDateTime.Month == 2 ? "visible" : "invisible")">
                <Dropzone class="card-dropzone w-100">
                </Dropzone>
            </div>

            @*add more dropzone for the others months ....*@

        </div>
```

**Comment by ssanga** [comment]
Hi @mattosaurus I have solved a similar issue this way:

```
<Dropzone Name="@DropName">
</Dropzone>

public string DropName
{
        get => new Guid().ToString();
        set => DropName = value;
}
```

**Comment by mattosaurus** [comment]
Hi @ssanga, thanks for sharing. I'll give this a go when I get a chance.
