### ISSUE TITLE
Wrong position when drag is aborted

### ISSUE THREAD

**Issue by frankabbruzzese** [Postlagerkarte/blazor-dragdrop#15]
When an element is dragged over a list the dragged element is added to the new list to show where it would be dropped. However, when the element leaves the list it is not returned in its original position, so if the drag operation is aborted element doesn't return to its original position, but in the last position it had in the last list it was dragged over.

**Comment by Postlagerkarte** [comment]
Hello @frankabbruzzese  , 
sorry but it is currently not possible to determine if a drag operation was cancelled. Usually one could use the dropEffect property to determine if a  drag was cancelled but Blazor does not provide accurate access to this property. 

This is tracked at https://github.com/dotnet/aspnetcore/issues/18754

**Comment by neildonkin** [comment]
Thanks for this great library 👍

Until the underlying Blazor issue is fixed, is it possible to use the keydown event to know when the esc key is pressed and the drag is cancelled?

**Comment by Postlagerkarte** [comment]
@neildonkin :  With 2.0 you have full control over the underlying list and thus you can restore you list when the esc key is pressed.
