### ISSUE TITLE
[Question] OrderPossiton not Available ?

### ISSUE THREAD

**Issue by danijel88** [Postlagerkarte/blazor-dragdrop#161]
Hello,
I saw old conversation about Order Position, is that still available , because when I try `OnItemDrop="@((d,i)=>d.OrderPosition)"`
d.OrderPosition can not be found.
Anyway, I need to see which position in list belong to the item, so I can save in that way, I need to track sequence of item.
So I want to add Item 1 to Item 10, and when I move Item 10 to Item 5, want to have correct written sequence .

Item 1 - #1
Item 2 - #2
Item 3 - #3
Item 4 - #4

When I move Item 2 down on position of Item 4, I should have
Item 1 - #1
Item 3 - #2
Item 4 - #3
Item 2 - #4

Or if I move Item 1 till end of list
Item 3 - #1
Item 4 - #2
Item 2 - #3
Item 1 - #4

Or opposite.

**Comment by Postlagerkarte** [comment]
It was removed because you can check you source for the position of the items,  e.g. inside the OnDrop you can check myList.IndexOf(droppedItem)

**Comment by Postlagerkarte** [comment]
If you don't have to many items you can just adjust all items at once, so no need to keep track of the replaced items, etc:

    public void OnDrop(TodoItem todo)
    {
        foreach(var myToDo in MyToDoList)
        {
            myToDo.Position = MyToDoList.IndexOf(x);
        }
    }

**Comment by danijel88** [comment]
Yes, that works. Thanks.

**Comment by NessfertIndia** [comment]
Can you post the example of OnDrop  please @danijel88  / @Postlagerkarte 
Looks like OnDrop  event   is not available with  <Dropzone , instead i can see one called OnItemDrop 
The ultimate aim is just to read the new order of items in the DropZone

**Comment by danijel88** [comment]
Hello,
Sorry on late replay, but was on holiday. Yes, now it is used OnItemDrop.  `OnItemDrop="@(p => OnItemDrop(p))"`
