### ISSUE TITLE
Before and After of Draggable item position to get 

### ISSUE THREAD

**Issue by TT241PGS** [Postlagerkarte/blazor-dragdrop#18]
How are we going to define the initial position and final state of position for different Drop Zone ?

**Comment by Postlagerkarte** [comment]
Hi @TT241PGS ,  not sure I understand your ask - can you explain your use case in a bit more detailed?

**Comment by TT241PGS** [comment]
I will  have 3 dropzone, On the component loaded, draggable item will be passed with drop zone name and position , the user will drag and drop according to their desire . Upon confim click event,want to store back the new dropzone and positon. How could I achieve it ?

**Comment by Postlagerkarte** [comment]
Take a look at https://github.com/Postlagerkarte/blazor-dragdrop/issues/11

**Comment by TT241PGS** [comment]
Thank you so much ,It works . God bless you!!
