### ISSUE TITLE
Read new order

### ISSUE THREAD

**Issue by buzzer83** [Postlagerkarte/blazor-dragdrop#19]
First I wanted to congratulate you on this package. I am starting to use it and I have created simple a sortable list and a function to add a new element. My problem is that I would like to get the final order of the items by for example a button click, but I have no idea to do it. 
```
<Dropzone>
@foreach (ProvaClasse item in lista)
 {
      <Draggable>
           <li  class="list-group-item mt-2 mb-2"> @item.DicNome[1] </li>
      </Draggable>
}
</Dropzone>
```
```
@code{
    List<ProvaClasse> lista;
    protected override void OnInitialized()
    {
        lista = _dbProvaClasse.Lista();
    }
}
```
TY

**Comment by Postlagerkarte** [comment]
Hi @buzzer83  - thank you for contacting me.

Take a look at https://github.com/Postlagerkarte/blazor-dragdrop/issues/11

**Comment by buzzer83** [comment]
sorry, I don't have read this
