### ISSUE TITLE
Problem with draggable item sizing

### ISSUE THREAD

**Issue by AnaStepic** [Postlagerkarte/blazor-dragdrop#20]
I am using Bootstrap and have 4 columns on my page that are filled with cards. I turned them into drop zones and draggables by making Dropzone a child of the column and draggable parent of the card:

```
<div class="row">
            <div class="col">
                <Dropzone>
                    <MyCard1 />
                </Dropzone>
                    
            </div>
            <div class="col">
                <Dropzone>
                    <MyCard2/>
                    <MyCard3/>
                </Dropzone>
            </div>
            <div class="col">
                <Dropzone>
                    <MyCard4/>
                </Dropzone>
                
            </div>
            <div class="col">
                <Dropzone>
                    <MyCard5/>
                    <MyCard6/>
                </Dropzone>
            </div>
        </div>
```

MyCard is basically this:
```
<Draggable>
    <div class="card shadow mb-2">
        <div class="card-header">
            <h6 class="m-0 font-weight-bold">@Title</h6>
        </div>
        <div class="card-body">
            @ChildContent
        </div>
    </div>
</Draggable>
```

Drag and drop functionality works. However, for some reason, the original width of my cards is changed to be the same width as the column.

How it was before I made things draggable:
![image](https://user-images.githubusercontent.com/7997858/80612343-21ebe500-8a3c-11ea-8063-8fbe0e7e13a1.png)

How it turned after I made things draggable:
![image](https://user-images.githubusercontent.com/7997858/80612225-f8cb5480-8a3b-11ea-8239-dbb52c7e2d53.png)

Do you have any idea what might be causing the issue and how to resolve it?

P.S. I love what you are doing with this library and would very much love, love, love it if you continued to develop it, at least to resolve/add some of the really necessary stuff

---
Edit:
I think I understand why this is happening. Those cards that are half in width are placed in a separate div which is then segmented into two columns.

I think this wouldn't be solved so easily without nesting of draggable items. Nesting is already mentioned in https://github.com/Postlagerkarte/blazor-dragdrop/issues/8#issue-571586765
however, I think our meaning of nesting is different. In my case, I want to drag and drop something from a drop zone which is inside of a drop zone, to its parent drop zone.

Or do you have other ideas how this could be accomplished?

**Comment by Postlagerkarte** [comment]
Hi @AnaStepic  - thank you for contacting me.

You are correct that each card is placed into a separate div. This is what makes the card draggable.  If you apply a style to that div you get the layout you desire:

![image](https://user-images.githubusercontent.com/8482283/80637053-af403100-8a5e-11ea-9afd-379788bddabb.png)

I understand that applying this style is not easy at the moment - this has already been raised #13 here. 

Would this help solve your issue?

**Comment by AnaStepic** [comment]
Thanks for the response. 

Placing a style to change the width would of course work, but not exactly the same as it is now. It would require a redesign of how things are positioned and containers they are in. But I get what you are saying, if cards could be placed within the same container while retaining the layout and sizing that they should have, then there should be no problem with how dragging works. I'll give it a try. 

Speaking of which, it would indeed be handy if you could expose a property that would let us add css classes to the draggable div.

**Comment by Postlagerkarte** [comment]
If you update to 1.1.7 you can apply custom attributes to Draggables:

`<Draggable class="myFooBar1 myFooBar2" style="width:20px">`

**Comment by AnaStepic** [comment]
Yeah, saw it and updated to it. Works wonderfully. Thank you very much. I managed to achieve my mentioned goal now that I can give draggables a custom class.
