### ISSUE TITLE
Child content of Draggable is not redrawing properly

### ISSUE THREAD

**Issue by AnaStepic** [Postlagerkarte/blazor-dragdrop#21]
I recently noticed that some of my components aren't redrawing properly even when I force a redraw with StateHasChanged(). Things that used to be perfectly responsive suddenly don't change at all. The methods are getting called, all the code that should be executed still executes. It appears that only that change isn't being shown visually, eg. the components aren't getting redrawn.

I hunted down through my git commit history and found the exact moment where things stopped working was when I added Drag & Drop into my project.
Thus the only code change between the commit that works perfectly fine and the commit that doesn't is including drag & drop into my project (importing the package through nuget, adding services.AddBlazorDragDrop() into Startup, adding using Blazor.DragDrop.Core into imports, adding the drag and drop css file to _Host) and then wrapping <Draggable> and <Dropzone> around my existing HTML code.

The hierarchy of my page is like this:

Index.razor has the dropzones and inside them I use my custom components like this:

Index.razor
``` HTML
 <div class="row">
            <div class="col dashboard-col">
                <Dropzone Class="row clear-min-height dashboard-row" Name="Column1">
                    <LogWordsWidget />
                </Dropzone>
           ....
```

My custom components are using another custom component like this:
``` HTML
<Card Title="Log Words">
      content
</Card>
```

And then, that card custom component is using Draggable:

``` HTML
<Draggable>
    <div class="card shadow mb-2">
        <div class="card-header">
            <h6 class="m-0 font-weight-bold">@Title</h6>
        </div>
        <div class="card-body">
            @ChildContent
        </div>
    </div>
</Draggable>
```

Currently, I am forced to remove drag & drop from the project because it breaks the functionality of my components. 

Do you have any idea what might be going wrong? As of now, I've only tried moving services.AddBlazorDragDrop() up and down the ConfigureServices method to no effect.

**Comment by Postlagerkarte** [comment]
Hi @AnaStepic  - thanks for bringing this to my attention. 

Are you able to reproduce this in a minimalstic project that you can provide me for debugging?

**Comment by AnaStepic** [comment]
Yes. I just created a new Blazor project in Visual Studio and installed Drag & Drop.

I edited Index.razor and created two components: MyComponent & Card

If you run the program, you'll see these two cards:
![image](https://user-images.githubusercontent.com/7997858/80752221-6e621e00-8b2b-11ea-89a5-d37cc2596f75.png)

Both the left and right cards have the exact same code. The only difference is that in the left card, that code is placed in MyComponent.razor, while in the right case, the code is pasted in the Index.razor

If you click on "Click me to toggle state", the text below should change. And it does, on the right card, but not on the left. If you put a breakpoint in the code, you'll see that the click method does get called, but the rendering of the card isn't updated. It won't update even if you call StateHasChanged()


Index.razor:
``` HTML
@page "/"

<div class="row">
    <div class="col">
        <Dropzone Class="row" Name="Column1">
            <MyComponent />
        </Dropzone>

    </div>
    <div class="col">
        <Dropzone Class="row" Name="Column2">
            <Card Title="Card">
                <a @onclick="Clicked">Click Me To Toggle State</a>

                @if (_toggle)
                {
                    <p class="text-danger">I have been toggled</p>
                }
                else
                {
                    <p class="text-primary">I have not yet been toggled</p>
                }
            </Card>
        </Dropzone>
    </div>
</div>
@code{
    bool _toggle = true;

    void Clicked()
    {
        _toggle = !_toggle;
    }
}
```

MyComponent:
``` HTML
<Card Title="My Component">
    <a @onclick="Clicked">Click Me To Toggle State</a>

    @if (_toggle)
    {
        <p class="text-danger">I have been toggled</p>
    }
    else
    {
        <p class="text-primary">I have not yet been toggled</p>
    }
</Card>

@code {
    bool _toggle = true;

    void Clicked()
    {
        _toggle = !_toggle;
    }
}
```

Card:
``` HTML
<Draggable AllOtherAttributes="@_attributes" Name="@Title">
    <div class="card shadow mb-2">
        <div class="card-header">
            <h6 class="m-0 font-weight-bold @TitleColor">@Title</h6>
        </div>
        <div class="card-body">
            @ChildContent
        </div>
    </div>
</Draggable>
@code {
            [Parameter]
            public string TitleColor { get; set; } = "text-primary";
            [Parameter]
            public string Title { get; set; }

            [Parameter] public RenderFragment ChildContent { get; set; }

            Dictionary<string, object> _attributes => new Dictionary<string, object>() { { "class", "col-12 dashboard-card" } };
}
```

The VS solution:
[Test.zip](https://github.com/Postlagerkarte/blazor-dragdrop/files/4560888/Test.zip)

**Comment by Postlagerkarte** [comment]
@AnaStepic  I can reproduce the error. 

If you change your code to 

```
           <Draggable>
                <MyComponent />
            </Draggable>
```
(and remove the draggable from the card component)

you can fix the issue. 

Unfortunately, there is no short-term fix to make it work otherwise.

**Comment by AnaStepic** [comment]
I see. So have to avoid putting draggable further down in the component hierarchy and figure out a way around it if needed.
