### ISSUE TITLE
Dynamically Injecting content into draggable items

### ISSUE THREAD

**Issue by HybridSolutions** [Postlagerkarte/blazor-dragdrop#22]
Haven't tested, your component so would it be possible to inject content into a draggable item and place it in a specific existing zone with some kind of ID or unique name? For what I see in your samples, you always need to declare dragabble items in razor file.

Would love to have this working with your component
[https://stevenknox.net/exploring-assembly-unloading-in-net-core-3-0-by-building-a-simple-plugin-architecture/](url)

**Comment by Postlagerkarte** [comment]
Hi @HybridSolutions , 

I assume this will not work.  As you can read in #21 it is currently necessary to have the Dropzone and Draggable as a root element and you will run into issues if you put them down further in the component hierachy.

However, I encourage you to play around and test it out - let my know your findings please!
