### ISSUE TITLE
Programmatically move draggable to a dropzone

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#25]
Hi!

Is there a way to move a draggable from one dropzone to another one? 
Preferably in a way that OnDrop() is called in the destination dropzone. 
(I want to achive that if a draggable is clicked, then it is moved automatically.)

Thanks.

**Comment by Postlagerkarte** [comment]
Hi @kristof12345 ,

yes this is possible.

Source Dropzone:
```
        <Dropzone>
            <Draggable>
                <li @onclick="()=>OnClickHandler(context)" class="list-group-item">Cras justo odio (order-pos: @context.OrderPosition)</li>
            </Draggable>
          </Dropzone>
```
Target Dropzone:
```

<Dropzone Name="MyOtherDropzone">

</Dropzone>
```

And this code :

```
    public void OnClickHandler(DraggableItem item)
    {
        Service.RemoveDraggableItem(item);
        item.DropzoneId = Service.GetDropzoneOptionsByName("MyOtherDropzone").DropzoneId;
        Service.RegisterDraggableForDropzone(item);
        StateHasChanged();
    }
```

**Comment by kristof12345** [comment]
Hi! 
Thanks for the answer. 
Initially it works, but after I DRAG (manually) an item, nothing happens when clicking an item. It might be because the items are generated in a foreach loop like in #6 .

Strange fact that if only 1 item is left in the source area the click works even after draging.

Any idea on that? Thanks.

**Comment by Postlagerkarte** [comment]
@kristof12345  Do you have a minimalstic project in a github repository?  I will take a look then.

**Comment by kristof12345** [comment]
This is the most minimalistic project I could create:
https://github.com/kristof12345/DragAndDropDemo/tree/master/DemoApp

**Comment by Postlagerkarte** [comment]
Try this:

```
    private void HandleClick(DraggableItem item)
    {

        var targetId = DragDropService.GetDropzoneOptionsByName("Target").DropzoneId;
        DragDropService.ActiveItem = item;
        DragDropService.DropActiveItem(targetId);
        
    }
```

**Comment by kristof12345** [comment]
It works. Thanks a lot!
