### ISSUE TITLE
Get DropzoneId

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#26]
Hi!

If there are more dropzones which Id is returned by DragDropService.GetDropzoneId()?

**Comment by Postlagerkarte** [comment]
Hi @kristof12345 ,

GetDropzoneId is not meant to be public. It is used internally to create new dropzone ids.

I will make it private in the next release.

Why do you need access to the dropzone id?  You can always assign a name to your dropzone and access the dropzone and its items via that name later.

**Comment by kristof12345** [comment]
Actually I wanted to achive this:
DragDropService.GetDropzoneOptionsByName(Question.Title).DropzoneId;
