### ISSUE TITLE
Get draggable item in OnDrop()

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#28]
Hi!

How to get the current draggable item in OnDrop()?

Thanks.

**Comment by Postlagerkarte** [comment]
Hi @kristof12345 ,

not really possible at the moment because the current signature is HandleDrop(dynamic d, int i). 

I have already planned to change it to HandleDrop(DraggableItem item) with the next release.

**Comment by Postlagerkarte** [comment]
@kristof12345  Can you explain what you like to do with the DraggableItem? ( the current signature gives you access to the tagged object data and the order position ). I like to understand your use case a bit more.

**Comment by kristof12345** [comment]
I originally wanted to rearrange the items from code after dropping an item. This would be more straightforward in OnDrop(). 

Using dragableitem parameter would also mean a more unified api (with the “context” you suggested to be used in #25 ). 

Everything that I wanted can be done through DragDropService. (Some documentation on that would make this library even better. )

**Comment by Postlagerkarte** [comment]
Thanks for the explanation. Makes perfect sense. I changed the signature accordingly.
