### ISSUE TITLE
OnDrop d-value is always null

### ISSUE THREAD

**Issue by samihuutoniemi** [Postlagerkarte/blazor-dragdrop#30]
`<Blazor.DragDrop.Core.Draggable OnDrop="(d, i) => OnDrop(d, i)">
...
</Blazor.DragDrop.Core.Draggable>`

`public void OnDrop(dynamic d, int orderPosition)
        {
        }`

In the case above the orderPosition seems to always be correct, but d is always null. Is it supposed to be a reference to what I dragged? 

I saw in another post that you are working on something, but in the meanwhile...

**Comment by nicolassargos** [comment]
In fact, the dynamic parameter ("d" in your case) is the Tag of your Draggable object.

**Comment by Postlagerkarte** [comment]
Due to the callback creating confusion I changed it to match the suggestion from #28 -  it is now `public void OnDrop(DraggableItem item) { } `
