### ISSUE TITLE
List Items are not getting cleared

### ISSUE THREAD

**Issue by bancroftway** [Postlagerkarte/blazor-dragdrop#31]
I have a component which exposes a property "Items"  and inside the component, I loop through the Items property and build the draggable list.

This component's parent component has a dropdown, and when a user selects an item in the dropdown, I lookup records that match the dropdown's selected value; I have bound this result to the inner component's "Items" property.

As the user selects different items in the dropdown, the list inside the component keeps growing, instead of showing only the current set of Items.

I have verified this issue is related to the blazor-dragdrop library, because when I remove the DropZone and Draggable tags from the component, then the list behaves as expected. Please help. Thanks

**Comment by Postlagerkarte** [comment]
Hi @bancroftway ,

have you cleared he Dropzone before assigning the new items? Check #23

**Comment by bancroftway** [comment]
In the example I cited above, where would I write the code for  clearing the dropzone? I tried OnParameterSetAsync, but got this error:

`Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Sequence contains no matching element
System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) <0x321ea60 + 0x0011a> in <filename unknown>:0 
  at Blazor.DragDrop.Core.DragDropService.ClearDropzone (System.String dropzoneName) <0x3217a68 + 0x00030> in <filename unknown>:0 
  at DPlan.Client.UIComponents.SkidPatternCmp.OnParametersSetAsync () [0x00001] in C:\Projects\UIComponents\SkCmp.razor:64 
  at Microsoft.AspNetCore.Components.ComponentBase.CallOnParametersSetAsync () <0x2d26980 + 0x00014> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2d26380 + 0x00146> in <filename unknown>:0 `

**Comment by Postlagerkarte** [comment]
Did you pass the correct Dropzone Name?

Nevertheless, If you can provide a small example project I can take a further look at the issue.

**Comment by bancroftway** [comment]
I have a reproduction [here](https://github.com/bancroftway/dragdropissuerepro).

In this project, from the Customers dropdown, first select Customer1, and then Customer2. The Customer2's orders get appended to DropZone as shown in screenshot. I am wondering, where exactly would I code the Dropzone.Clear in this case.

![image](https://user-images.githubusercontent.com/13262438/83908455-c5f83880-a72c-11ea-9cc5-782ca51d038e.png)

**Comment by Postlagerkarte** [comment]
Try

```
private async Task HandleCustomerSelection(ChangeEventArgs e)
    {
        if (e.Value != null && !string.IsNullOrEmpty(e.Value.ToString()))
        {
            DragDropService.ClearDropzone("dZone");
            SelectedCustomerId = new Guid(e.Value.ToString());
            StateHasChanged();
        }
    }
```

**Comment by bancroftway** [comment]
@Postlagerkarte  while the provided solution works, it is a bit unclean, in that the parent component is intimately aware of the child component's inner workings, breaking encapsulation.

Secondly, if the Order has a property IsDeleted to soft-delete an order, and the requirement is that when user presses 'Delete' button on an order, the order should be removed from the list, in such a case, how would we handle clearing and re-binding the dropzone, from within the component?

**Comment by Postlagerkarte** [comment]
Hi @bancroftway , I agree with you but I am not planning to do any major work on the library except bugfixes until the Blazor Team has finalized how DragDrop looks like in .NET 5 Blazor.

For the second point - did you check #6 ? It shows how to remove an item when a users presses delete.
