### ISSUE TITLE
Dragging Images in Firefox Fails

### ISSUE THREAD

**Issue by dsmolen1** [Postlagerkarte/blazor-dragdrop#33]
My app has draggable items that include an image tag. It works well in Chrome and Edge, but in Firefox, when the item is dropped, the image is displayed in the active tab and the drag/drop doesn't complete. I suspect this is a Firefox issue, but I wondered if you had any ideas about it. The attached solution will show the problem if you use Firefox as the browser. Thanks for looking at this and for your very cool package.

[FireFoxDragDrop.zip](https://github.com/Postlagerkarte/blazor-dragdrop/files/4748002/FireFoxDragDrop.zip)

**Comment by Postlagerkarte** [comment]
Hi @dsmolen1 - thank you for filling this issue. 

Try the new 1.1.9 and let me know if it issue is resolved.

**Comment by dsmolen1** [comment]
Yes, it is resolved! Another quick question: is there a way to overlap 
the images? Looks like I would need to style the divs that the package 
inserts. Thanks again.

The best lack all conviction, while the worst
Are full of passionate intensity.

------ Original Message ------

**Comment by dsmolen1** [comment]
I figured out how to overlap the images, so ignore my earlier question. 
Thanks again.

The best lack all conviction, while the worst
Are full of passionate intensity.

------ Original Message ------

**Comment by Postlagerkarte** [comment]
Great!

If you need further styling you can always assign classes directly to the draggable:

`<Draggable class="myFooBar1 myFooBar2" style="width:20px">`

**Comment by dsmolen1** [comment]
I've run into another issue: I have a single dropzone with several 
draggable images. As long as the images are unchanged, everything works. 
When an image is added or removed from the dropzone, however, things get 
a bit crazy. Removed images keep appearing and new images don't show up.

Is there a way to handle this scenario? Thanks for your help. Let me 
know if you'd like a demo of the problem.

Don

The best lack all conviction, while the worst
Are full of passionate intensity.

------ Original Message ------

**Comment by Postlagerkarte** [comment]
Did you check #6 ? When you remove an item from the underlying list the DragDropService needs to be informed about it.
