### ISSUE TITLE
Question: How to highlight the row where draggable item is going to be dropped

### ISSUE THREAD

**Issue by bancroftway** [Postlagerkarte/blazor-dragdrop#34]
@Postlagerkarte in your opinion, what would be the way to achieve highlighting of the row (such as by darwing a line)  where the draggable is going to be dropped, as shown in this demo: https://codepen.io/retrofuturistic/pen/tlbHE

Thanks

**Comment by Postlagerkarte** [comment]
Hi @bancroftway ,  depending on the use case maybe a simple css will do:

```
.draggable-intransit {
    border-top: 5px solid #ff0000;
    padding-top: 20px;
}
```
