### ISSUE TITLE
Dragging doesn't work properly on iPhones

### ISSUE THREAD

**Issue by ddashwood** [Postlagerkarte/blazor-dragdrop#35]
I'm looking into using your library, but it doesn't seem to work correctly on iPhones and I'm hoping there might be a quick fix for it.

I've made a [recording of me trying to use your demo website on my iPhone](https://imgur.com/a/xYKzfgZ), and as you can see, when the item is dragged around the screen, the whole screen moves, which makes it difficult to drag accurately.

Do you have any idea how to fix this? Thanks!

**Comment by Postlagerkarte** [comment]
Hi @ddashwood , thank you for contacting me.
Sorry to say, but mobile support is not included in the library itself. If you are using a pollfyfil library, e.g. mobile-drag-drop you should open a ticket there.
