### ISSUE TITLE
What are exactly the limitations of this library?

### ISSUE THREAD

**Issue by crussman** [Postlagerkarte/blazor-dragdrop#36]
Greetings!

First of all, it's not precisely an issue, but I wanted to clear some doubts respecting to the first advertisement of the repo:

_!This library is suitable if you need to make a small set of items draggable. It is not suitable to for large lists_

I'm creating a map for a game in WebAssembly which basically is a background image, grids drew over it, and a div for every grid that will contain a single image which can be dragged over other grids, though a grid can't contain more than one image, but, due the grid numbers goes from 600 to 10.000, I want to know if it'll be a bad idea to use this library as the basis for the drag & drop operations...

Thanks in advance!

**Comment by Postlagerkarte** [comment]
HI @crussman ,

I think you will run into performance problems.  You can read #29 for details . However, it should be easy to try it out because the code you have to add / remove to apply drag and drop should be minimal.

**Comment by crussman** [comment]
Hey @Postlagerkarte 

Thanks for your quick response!

I'll read about it

Regards!
