### ISSUE TITLE
Cannot use the library on razor page in a project whose name ends with the word "Blazor"

### ISSUE THREAD

**Issue by TarasBounty** [Postlagerkarte/blazor-dragdrop#37]
**Preconditions:** project whose name ends with the word "Blazor". _For example: MyProject.Blazor._

using Blazor.DragDrop.Core; - works as expected in .cs file.

If I'm trying to write the same code in razor page, the following error appear:
![image](https://user-images.githubusercontent.com/15182848/86581424-c3d20580-bf88-11ea-9c69-fce64c8fc0c9.png)

If I do it inside tag (<Blazor.DragDrop.Core.Dropzone></Blazor.DragDrop.Core.Dropzone>), compilation error appears:
![image](https://user-images.githubusercontent.com/15182848/86581788-465ac500-bf89-11ea-995f-cb13143468f8.png)

Is it possible to use it in a project whose name ends with the word "Blazor"?

**Comment by stsrki** [comment]
The same thing is happening to me. I have Blazor in project namespace, eg. `Company.Blazor.MyProject`. And I cannot use library since I cannot add `Blazor.DragDrop.Core` namespace or define `<Dropzone>` component name in razor file.

**Comment by Postlagerkarte** [comment]
This should be fixed in 2.0
