### ISSUE TITLE
How to use OnDrop property?

### ISSUE THREAD

**Issue by gaffkins** [Postlagerkarte/blazor-dragdrop#4]
Hi. How to use OnDrop property? I try use OnDrop="(d) => OnDrop(d) and then 
public void OnDrop(DraggableItem item)
    {
        Console.WriteLine( item.OrderPosition);
    }

but this is not work.
Best.

**Comment by Postlagerkarte** [comment]
Hello @gaffkins 

use a handler that expects a dynamic

`public void OnDrop(dynamic item)`

The value that is passed is the value that you assigned via the Tag property.

e.g.

  ` <Draggable Tag='new { Id = 12, Name = "MyNameForThisItem" }' OnDrop="OnDrop">`

and

```
    public void OnDrop(dynamic d)
    {
        Console.WriteLine(d.Id);
        Console.WriteLine(d.Name);
    }
```

**Please note:**
Currently the OnDrop event is only raised if you drag the item to a different dropzone. No event is raised if the item is dragged within the same dropzone.  I am going to fix that with the next release.

**Comment by devgibsonsp** [comment]
Is this syntax still the preferred method?

I am getting a
Error	CS0123	No overload for 'OnDrop' matches delegate 'Action<dynamic, int>'	RouteConfiguration.Client	

Error when using your example
