### ISSUE TITLE
System.ArgumentException: Rendering dropzones by boolean flag

### ISSUE THREAD

**Issue by alex28012001** [Postlagerkarte/blazor-dragdrop#41]
I have 2 dropzones and a boolean flag. If the flag is false, the fist dropzone will be shown. The second dropzone with true.
A order of actions for reproducing the exception:
1) rendering a page with the first dropzone (flag is false)
2) switching the flag, rendering the second dropzone
3) switching the flag, appering the exception
![image](https://user-images.githubusercontent.com/25509535/87565507-65b0cb00-c6ca-11ea-88df-7a74a67b3e17.png)

**Comment by Postlagerkarte** [comment]
Hi @alex28012001 : Thanks for contacting me.  Please upgrade to 2.0 and let me know if you still have issues.
