### ISSUE TITLE
How to get sorted List on click?

### ISSUE THREAD

**Issue by flixius** [Postlagerkarte/blazor-dragdrop#42]
Hi,
first of all thank you for your work, @Postlagerkarte @daghb 

I would like to know how it is possible to retrieve the data of the sorted list on a button click. 

On a button click event, the List<T> I gave to the Dropzone still has the initial sort order. 

I checked the Demo pages but didn't see an implementation of that, unfortunately.

**Comment by flixius** [comment]
Finally I found the solution. Here is the code if anyone else has the same question: 

`
<Dropzone Name="X">
        <ul class="list-group">
            @foreach (var club in clubsToShow)
                {
                    <Draggable Name="@club" Tag='new { Id = club.Id, Name = club.Name}'>
                        <li class="list-group-item">@(context.OrderPosition+1)<span>.</span> @club</li>
                    </Draggable>
                }
            </ul>
    </Dropzone>

<button @onclick="@Submit" class="btn btn-primary">Submit</button>

private void Submit()
    {
        var items = DragDropService.GetDraggablesForDropzone("X");
        foreach (var draggableItem in items)
        {
            Debug.WriteLine(((object)draggableItem.Tag.Id).ToString() + " " + ((object)draggableItem.Name).ToString());
        }
    }
`

**Comment by Postlagerkarte** [comment]
@flixius : Thanks for contributing! 

I suggest you upgrade to the new version which makes the task much easier.
