### ISSUE TITLE
Elements within a Draggable are not interactable

### ISSUE THREAD

**Issue by elylv** [Postlagerkarte/blazor-dragdrop#43]
I am trying to create a treeview that allows drag and drop using your control.
I am making each node of my treeview a Draggable, however, this seems to prevent interaction with the contents.
i.e. I have something like:
<Draggable>
 <div class="tree-node-item" @onclick="ExpandNode">Expand</div>
</Draggable>

The @onclick event is firing, but it attempts to change the contents of the Draggable (e.g. changing CSS class) which is not working.  It seems as if the contents of the Draggable can only be static, so we can't have it contain any kind of changeable component.  Is that right?

**Comment by Postlagerkarte** [comment]
Hi @elylv - thanks for contacting me!
Please update to the latest version and let me know if you still have issues.
