### ISSUE TITLE
Does the lib support drag drop items between dropzones without changing items in the main dropzone?

### ISSUE THREAD

**Issue by TarasBounty** [Postlagerkarte/blazor-dragdrop#44]
I would like to implement smth like Toolbox in WPF\Xamarin:

![Screen Shot 2020-08-04 at 16 00 45](https://user-images.githubusercontent.com/15182848/89297716-feed5480-d66c-11ea-9c4d-ad0f04e3ebcf.png)

For example: I drag item from zone1 and drop it in zone2. Items in zone1 have no changes. Items in zone2 add item from zone1.
It is possible?

**Comment by Postlagerkarte** [comment]
Hi @TarasBounty  - currently the item is removed from the source dropzone - there is no "copy" option yet.  Have you tried  readding (a deep copy) of your item to your source list after the drop event?

**Comment by TarasBounty** [comment]
Thanks for your quick response! 

Yeap, I tried readding item to the source list. It adds an item to the end of the list. For example from the screenshot above, if I drag the button to the editor panel, the button goes to the end of the toolbox list after DataGridView. It is not what I expected.
Maybe I need to know initial position in first list. Also if I dragged a button to the editor, I also want to drag one more button, but in list button already exists and it is not copying.

Do you have any plans to implement the "copy" option?

**Comment by Postlagerkarte** [comment]
I added support for this.  If you want the item to be copied instead of moved you can now make use of the "CopyItem" attribute: 

```
<Dropzone CopyItem="(item)=> { return new TodoItem() {Titel = item.Titel}; }" Items="MyThirdList" TItem="TodoItem" OnItemDrop="@((i)=>lastdropped = i)">
    <div style="border: 2px solid black">
        @context.Titel
    </div>
</Dropzone>
```
The CopyItem attribute expects a method telling the dropzone how to create a copy of the item. It receives the currently active item as input.

**Comment by TarasBounty** [comment]
@Postlagerkarte great! Thanks for your work! I will check and use it!

**Comment by TarasBounty** [comment]
I am trying to use logic like this. 
In the loop I create 3 zones, then from one list (_LayoutItems_) I am trying to get necessary items with LINQ. 


```
@foreach(var zone in _dropzones)
{
    var items = LayoutItems.Where(x => x.ZoneName == zone).ToList();
    <Dropzone Items="items" TItem="MyItem" OnItemDrop="(i) => i.EditorDropzone = zone">
        <div style="border: 2px solid black"></div>
    </Dropzone>
}
```

All displayed as expected and items can drag-drop between zones. But I can not change items order in any zone.
I understand why it can't be done. But maybe you can get advice how I can do logic like this? It is possible?

**Comment by Postlagerkarte** [comment]
@TarasBounty :  Copy items should work now - thus I am closing this issue - if copy does not work,  let me know so I can reopen.  For your second issue , if is still relevant, please be open a new issue. Thank you!
