### ISSUE TITLE
More customizable Div's please

### ISSUE THREAD

**Issue by erturkd** [Postlagerkarte/blazor-dragdrop#48]
On Dropzone.razor file, can you make the class of the div's more customizable please, with adding string parameters as:
[Parameter]
public string CustomCss { get; set; }

[Parameter]
public string CustomStyle { get; set; }

[Parameter]
public string CustomDragItemCss { get; set; }

[Parameter]
public string CustomDragItemStyle { get; set; }

_Then:_
div **style="@CustomStyle"** class="plk-dd-dropzone @GetStyleClass() **@CustomCss**"

_and also in the foreach statement:_
div draggable **style="@CustomDragItemStyle"** class="**@CustomDragItemCss**" @CheckIfItemIsInTransit(item) @CheckIfItemIsDragTarget(item) @CheckIfDragOperationIsInProgess()"

So we can add more customizable styles. Thank you very much.

**Comment by Postlagerkarte** [comment]
Hi @erturkd - thank you for contributing!

The idea is that you target plk-dd-dragged-over and plk-dd-in-transit with your own css. You would apply a style to p**lk-dd-dragged-over** to style the appearance of the currently dragged over style and to apply a style to **plk-dd-in-transit** to style the currently active item that is beeing dragged.  Would that work for you?

I would also like to have more build-in styles to make it easy for people without design/css knowledge:

` <Dropzone Items="MyItems" Style="DragDropStyle.NiceStyle">`

**Comment by erturkd** [comment]
I checked plk-dd-dragged-over and plk-dd-in-transit and they don't solve my problem.

Actually I am trying to do a horizontal and then vertical draggable image list like this:
[https://bit.ly/2DurT0Z](url) and [https://bit.ly/33AAhqr](url)

With version 1.x I did something like:
Dropzone Name="dropZone" **class="card-columns"**

and

Draggable  **class="card rounded-top shadow-0 d-inline-flex mr-2" style="width: 200px;"**

and I did this effect. But version 2.x creates it's own divs which I can do just vertical dropdown items. 

So if we can reach the Class and the Style of this two divs we can do this effect.

**Comment by Postlagerkarte** [comment]
You can now assign classes for dropzone via the class attribute. <Dropzone Class="myclass1 myclass2">  - I have not yet added something for wrapper div(s).  Still thinking about the best way to do it. Check the [flex demo](https://blazordragdrop.azurewebsites.net/flex) to see a basic example for horizontal dragging.

**Comment by erturkd** [comment]
It is perfect now. Thank you for your work.
