### ISSUE TITLE
DragDrop to an empty zone

### ISSUE THREAD

**Issue by buzzer83** [Postlagerkarte/blazor-dragdrop#49]
Hi @Postlagerkarte ,
I used version 1 in a case similar to your demo - twozones, but having an empty area in the second zone as a starting point and it worked fine. Are you planning to introduce this feature in this v2? If it's already there I'm sorry but I didn't understand how to use it.
ty

**Comment by Postlagerkarte** [comment]
Hi @buzzer83 ,

not sure I understand correctly but I just tried with an empty zone  (by clearing the items of the second dropzone):

![demo2](https://user-images.githubusercontent.com/8482283/89653459-6b639000-d8c7-11ea-9c3e-76fa713e6f58.gif)

Is this what you are looking for?

**Comment by buzzer83** [comment]
@Postlagerkarte Sorry for my bad english. Yes this is the idea, but a single item must be present in a single zone. In your example 
item4 is present in both lists.

**Comment by kristof12345** [comment]
On the demo site the same thing happened. But on local environment it works well for me.

**Comment by Postlagerkarte** [comment]
@buzzer83 : Please try again on the demo site.

**Comment by buzzer83** [comment]
@Postlagerkarte : it's very good. Do I have to wait for the update?, right?

**Comment by Postlagerkarte** [comment]
2.1.0 is available now
