### ISSUE TITLE
Mousewheel not working

### ISSUE THREAD

**Issue by isoindisystems** [Postlagerkarte/blazor-dragdrop#5]
Hello!
We have many elements in our lists, but we can´t use the mousewheel after started dragging an element.
What can we do about this?

**Comment by Postlagerkarte** [comment]
Hi @isoindisystems , thank you for contacting me.

This is currently not possible. Browsers do not send mousewheel events when a drag operation is in progress. I might add support for it but it would require a different approach to handle dragging of items.  

Currently lists will auto scroll if you drag an element to the edge of a container but for very large list this is indeed inconvenient.
