### ISSUE TITLE
Only on demo page: When draging an item to another dropzone it also stays in the original dropzone.

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#50]
When draging an item to another dropzone it also stays in the original dropzone.
This happens in Demo 3 and Demo 4 too. 

This might be an intended behaviour though. If so, is there a way to change it?

Thanks.

**Comment by kristof12345** [comment]
Strange, because it does not happen in local environment, only on the demo page.

**Comment by Postlagerkarte** [comment]
The deployment was out of sync. Can you confirm that the Demo Page works now?

**Comment by kristof12345** [comment]
Well now its indeed removed from the source list, but always added at the end of the destination list (no matter where I try to drag it).
