### ISSUE TITLE
Improvement: Spacing between items during drag

### ISSUE THREAD

**Issue by kristof12345** [Postlagerkarte/blazor-dragdrop#51]
Hi!

I love using v2, its much more straightforward. 
There is only one feature that I'm missing: when dropping an item between other two, in v1 there was automatically added some place for it (before releasing the cursor). I'll try to illustrate the difference:
v1:
<img width="845" alt="Képernyőfotó 2020-08-08 - 11 16 39" src="https://user-images.githubusercontent.com/43353335/89706821-7111b200-d969-11ea-8705-84f36de00a58.png">

v2:
<img width="742" alt="Képernyőfotó 2020-08-08 - 11 13 56" src="https://user-images.githubusercontent.com/43353335/89706823-753dcf80-d969-11ea-8ed5-a6312234a679.png">

If it could be done in v2, it would improve UX a lot.

Thanks. Keep on the great work!

**Comment by Postlagerkarte** [comment]
This is a good idea - I will build it in. If you activate instant replace mode it should already look the same as in the v1.

**Comment by Postlagerkarte** [comment]
@kristof12345 : I added support for this. You can also style the space between items if you don't like the defaults. You have to target the class `plk-dd-spacing-dragged-over` with a css selector.  By default a padding of 25px is applied.

**Comment by kristof12345** [comment]
Thank you! Can’t try it right now, only next week.

**Comment by kristof12345** [comment]
Thanks for the update!
