### ISSUE TITLE
Dropzone "freeze" after drag rejected.

### ISSUE THREAD

**Issue by TarasBounty** [Postlagerkarte/blazor-dragdrop#52]
So I forked your Demo project to reproduce the bug. 
You can check [the repository here](https://github.com/TarasBounty/blazor-dragdrop) and [last commit with the bug here](https://github.com/TarasBounty/blazor-dragdrop/commit/489d7b16d936a1b0bdd476799d21ec964eba27fb).

So I've just want to show a border on "active" item (on which user clicked). 
If you will run the project with my changes and go to "Demo 3" page, you can click on First dropzone items and they will have a red border. If you drop smth from a Second dropzone to First and click on items from First its also take red border.

Steps to reproduce:
1. Drag item from the Second dropzone (for example "item 10") move the mouse to First dropzone (not released the mouse button) and drop an item in the Second dropzone (where it initially located)
2. Now try to click on items from the First dropzone

Actual result: It's "freeze". Borders did not appear, To "unfreeze" just move some item in the First dropzone
Expected result: dropzone not freezes.

P.S. Thanks for your great work!

**Comment by TarasBounty** [comment]
Not fixed. I tried version 2.1.3 on my project and the same issue appears.
In your demo site, you can just add this styles:
```
.mt-2:hover {
    background-color: red;
}
```
And bug will reproduce

**Comment by Postlagerkarte** [comment]
@TarasBounty I tried to follow you above steps and it seems to work for me:

![bugrepro](https://user-images.githubusercontent.com/8482283/90493666-ec7e1b00-e142-11ea-842b-c76924e40016.gif)

What am I missing?

**Comment by TarasBounty** [comment]
@Postlagerkarte Hmm, so strange. Yeap, you do all right.
Check please Demo 3 page with styles which I mentioned above

![image](https://user-images.githubusercontent.com/15182848/90504591-fc552980-e159-11ea-8d30-ec4b925a3dde.png)
