### ISSUE TITLE
OnDrag hide or change opacity to 0 in original element like trello does. 

### ISSUE THREAD

**Issue by michelkommers** [Postlagerkarte/blazor-dragdrop#53]

**Comment by Postlagerkarte** [comment]
Use a custom style for this:

`<Dropzone Style="DragDropStyle.Custom">`

and add to you site.css e.g.: 

```
 .plk-dd-spacing {
    height: 10px;
}

 .plk-dd-spacing-dragged-over {
    padding: 25px;
}

.plk-dd-dragged-over  {
    background-color: lightgray;
    opacity: 0.6;
    animation: blinker 1s linear infinite;
}

 .plk-dd-dragged-over > div {
    background-color: lightgray;
    opacity: 0.6;
    animation: blinker 1s linear infinite;
}

.blink_me {
    animation: blinker 1s linear infinite;
}

 .plk-dd-in-transit {
    opacity: 0
}

.plk-dd-in-transit > div {
    opacity: 0
}
```

**Comment by michelkommers** [comment]
@Postlagerkarte I tryed this initially, but the style from the in-transit apply to both 'visual elements', the div that stays on original place and the one dragged.

see this post as a reference: https://stackoverflow.com/a/36385912/1546943

The key point is to listening to the drag event, instead of the dragstart.

PS; im asking for this cause for the user, sounds more 'natural' to see the original element disapear while dragging.

**Comment by Postlagerkarte** [comment]
@michelkommers  thank you for contributing!  

I just tried with the custom style from above and it looks like the original element is getting the zero opacity while the dragged element is not. 

![opacity](https://user-images.githubusercontent.com/8482283/90268522-6ec2c280-de57-11ea-9e6a-72b26e021710.gif)

You can see it more clearly if you use 

.plk-dd-in-transit {
    border: 5px solid red;
}

.plk-dd-in-transit > div {
    border: 5px solid red;
}

I agree that it looks more 'natural' to see the original element disapear while dragging.

**Comment by michelkommers** [comment]
@Postlagerkarte  thanks for the reply.

Here is applying to both, i will look in to my code, maybe something is conflicting, dont no.
Thanks
