### ISSUE TITLE
Empty dropzone visual representation enhancement 

### ISSUE THREAD

**Issue by doberman-ch** [Postlagerkarte/blazor-dragdrop#56]
Hi,

When dropzone is empty there is no way to make it looks similar to the spacing div and it is not clear (except cursor) that you can drop item in that area. 
It would be nice to keep one spacing div in empty dropzone, or maybe some more suitable solution. 

Version 2.1.1

Current behavior:
Drag&drop works correct, but there is no visual representation of it.
![image](https://user-images.githubusercontent.com/7737773/90355541-8047ce00-e001-11ea-8c09-f26c00938f9b.png)

Thanks

**Comment by Postlagerkarte** [comment]
Hi @doberman-ch ,

2.1.3 supports assigning an id to the dropzone.

`<Dropzone Id="SecondDropzone" Items="MyItems">`

You can then use a css selector for targeting the id and style the dropzone div. 

Is that feasible for you?

**Comment by doberman-ch** [comment]
Hi,
Thanks for quick response. It may work.
