### ISSUE TITLE
Draggable in a foreach is not deleted when removing an item from a list

### ISSUE THREAD

**Issue by SimonLeeCooper** [Postlagerkarte/blazor-dragdrop#6]
Hello!

I'm trying to use the Draggable component inside a foreach. However, when I delete an item from the list, the Draggable linked to this item is not deleted.

Here is my code :

```
<Dropzone>
	@foreach (TestStep step in testCase.Steps)
	{
		@step.StepNumber

		<Draggable @key="step">
			<div class="row card">
				<div class="col-sm-1">@step.StepNumber</div>
				<div class="col-sm-5">@step.Actions"</div>
				<div class="col-sm-5">@step.ExpectedResults</div>
				<div class="col-sm-1">
					<button class="btn btn-light" @onclick="(() => DeleteStep(step))">
						Delete
					</button>
				</div>
			</div>
		</Draggable>
	}
</Dropzone>

@code {
    [Parameter]
    public TestCase testCase { get; set; }

    private void DeleteStep(TestStep step)
    {
        testCase.Steps.Remove(step);
        StateHasChanged();
    }
}
```

Note that when deleting an item, the _StepNumber_  displayed before the Draggable are updated.
I tried to use _key_ on Draggable but it doesn't change the behavior.

Do you have a solution to be able to remove the Draggable linked to the deleted item without reloading the whole page?

Thanks.

**Comment by Postlagerkarte** [comment]
Hi  @SimonLeeCooper , thank you for contacting me.

Please upgrade to 1.1.1 and adjust your code like this:

```
<Dropzone>
	@foreach (TestStep step in testCase.Steps)
	{
		@step.StepNumber

		<Draggable @key="step">
			<div class="row card">
				<div class="col-sm-1">@step.StepNumber</div>
				<div class="col-sm-5">@step.Actions"</div>
				<div class="col-sm-5">@step.ExpectedResults</div>
				<div class="col-sm-1">
					<button class="btn btn-light" @onclick="(() => DeleteStep(step, context))">
						Delete
					</button>
				</div>
			</div>
		</Draggable>
	}
</Dropzone>

@code {

    [Inject]
    public DragDropService MyDragDropService {get; set;}

    [Parameter]
    public TestCase testCase { get; set; }

    private void DeleteStep(TestStep step, DraggableItem item)
    {
        MyDragDropService.RemoveDraggableItem(item);
        testCase.Steps.Remove(step);
        StateHasChanged();
    }
}

```

**Comment by SimonLeeCooper** [comment]
Hi @Postlagerkarte ,

It's working perfectly. Thank you :)

**Comment by kristof12345** [comment]
Hi! Where does the "context" come from?

**Comment by gaffkins** [comment]
After I added context I got error:
[CS0103] The name 'context' does not exist in the current context
Please help :)

**Comment by Postlagerkarte** [comment]
Hi @gaffkins - Show the relevant part of your code please.

**Comment by gaffkins** [comment]
<Dropzone AllowSwap="false" MaxItems="0" class="row" Name="FreeDropzone">
            @foreach (var item in FreeItems)
            {
                <Draggable Context="context" @key="item" class="col-6 mb-4" 
OnDrop="@OnPhotoDrop" @onclick="(()=>Remove(item, context))">
                    <div class="selected-photo @((item==1)?"active":"")" >
                        <img src="https://picsum.photos/400/300?random=@item"/>
                    </div>
                </Draggable>
            }
</Dropzone>

**Comment by gaffkins** [comment]
Ok I figuret out that I must use context inside component, for example
```
<Draggable Context="context" @key="item" class="col-6 mb-4" OnDrop="@OnPhotoDrop">
                    <div @onclick="(()=>Remove(item, context))" >
                    <div class="selected-photo @((item == 1) ? "active" : "")">
                        <img src="https://picsum.photos/400/300?random=@item"/>
                    </div>
                    </div>
                </Draggable>
```
