### ISSUE TITLE
Dropzones not responding properly with zero items

### ISSUE THREAD

**Issue by mwpowellhtx** [Postlagerkarte/blazor-dragdrop#70]
They do not seem to be responding quite right, or perhaps I am doing something incorrectly, which is more likely.

I've got a couple of dropzones configured, there are three actually, but this illustrates. I want to drag and drop the cards between zones. I can start the drag, but the drop does not seem able to locate the zone. Maybe the zone needs to be aligned with the parent element instead of the list section?

![image](https://user-images.githubusercontent.com/1824187/95023942-eccc6a00-064d-11eb-98bc-f8a04af050fe.png)

As you can see here, I am hunting for the dropzone but cannot find it in the current view. The demo samples work, but I think that is because they all contain at least one item. What would happen when a zone became empty of items?

![image](https://user-images.githubusercontent.com/1824187/95024031-87c54400-064e-11eb-9bf7-31f64ba6c484.png)

With code supporting the dropzones themselves:

```Razor
@foreach (var lane in new[] { JobLaneKind.Queued, JobLaneKind.Benched, JobLaneKind.Postponed })
{
    <div class="card">
        <div class="bg-light">@($"{lane}:")</div>
        <Dropzone TItem="Job" Items="this.Jobs[lane]" Accepts="@(x => true)" OnItemDrop="@(x => this.LastDroppedJob = x)" OnItemDropRejected="@(x => this.LastRejectedJob = x)">
            <JobView CurrentJob="@context" />
        </Dropzone>
        <hr />
    </div>
}
```

And the `JobView` is fairly self explanatory:

```Razor
<div class="card" style="border: 2px solid black">
    <p>@this.CurrentJob.Text</p>
    <p><small>@($"{this.CurrentJob.Id:D}")</small></p>
    <p><small>Updated: @($"{this.CurrentJob.UpdatedOn:yyyy-MM-dd tt}")</small></p>
</div>

@code {
    [Parameter] public Job CurrentJob { get; set; }
}
```

And which initialization starts out in life as the following. In production, of course, this would connect with some data source, repository, etc, but for now:

```Razor
protected override void OnInitialized()
{
    IEnumerable<Job> GetDefaultJobs()
    {
        for (var i = 0; i < 10; i++)
        {
            yield return new Job { };
        }
    }

    this.Jobs = GetDefaultJobs().GroupBy(x => x.CurrentLane).ToDictionary(x => x.Key, x => (IList<Job>)x.ToList());

    // And fill in whatever gaps may be there for jobless lanes.
    foreach (var lane in new[] { JobLaneKind.Queued, JobLaneKind.Benched, JobLaneKind.Postponed }.Except(this.Jobs.Keys))
    {
        this.Jobs[lane] = (IList<Job>)new List<Job> { };
    }
}
```

**Comment by Postlagerkarte** [comment]
Hi @mwpowellhtx - have you set a min height on the dropzone div? 

Here is the relevant style from the demo site: 

![image](https://user-images.githubusercontent.com/8482283/95024441-574bcd00-0683-11eb-9744-4ff052b0a9e2.png)

**Comment by mwpowellhtx** [comment]
Appreciate that I will have a look. Thank you.
