### ISSUE TITLE
Allows version of Accepts?

### ISSUE THREAD

**Issue by ThatRickGuy** [Postlagerkarte/blazor-dragdrop#77]
Accepts works great for preventing drops of specific items, but would it be possible to get a similar "Allows" to control what items can be dragged in the first place?

In my use case I have an existing list that is in priority order. I need to be able to add to that list, and move the new item around, without being able to move any of the other items. I can set the accepts to only allow the new item, but the old items can still be dragged, they just wont update after dropping them. Preferably, I'd rather they couldn't even be dragged.

**Comment by Postlagerkarte** [comment]
fixed by #80 and available in 2.2.1
