### ISSUE TITLE
Disable "Swap"?

### ISSUE THREAD

**Issue by ThatRickGuy** [Postlagerkarte/blazor-dragdrop#78]
If you drag an item up and hover over another item, the background item will pulse and dropping will swap the items. Is there a way to turn this functionality off? 

Also, the swap functionality ignores limitations of the Accepts inspection.

**Comment by koryphaee** [comment]
I'd also like this feature. I think, depending on the use-case, it can be more intuitive for the user.
I've looked at the source code a bit and it seems like a pretty fast and easy change (you only have to prevent `dragTargetItem` from being set in `OnDragEnter()`.
I would be willing to make a pull request if you want me to @Postlagerkarte.

**Comment by Postlagerkarte** [comment]
@koryphaee  @ThatRickGuy : 

I like the idea. To make it a bit more flexible I think a good approach is to extend the Accept Func to include a second in parameter:

`[Parameter] public Func<TItem, TItem, bool> Accepts `

The second in parameter is the targetItem and can be used like this:

` <Dropzone Items="MyToDoList" Accepts="(sourceItem,targetItem) => targetItem == null" >`

You probably have to move the  dragTargetItem out of the Dropzone.cs into the DragDropService to make it work.

The above should allow fine grained control upon which items a drop is allowed.

For visual styling:

I think a good approach is to modify the CheckIfItemIsDragTarget and make it return e.g. a plk-dd-dragged-over-denied in case the above func return false.

That way you can enable/disable different items as swappable und modify the css accordingly.

It should still be easy to change and I would appreciate if you @koryphaee  send a pull request - happy to help if you have issues implementing it.

**Comment by koryphaee** [comment]
Created the pull request: https://github.com/Postlagerkarte/blazor-dragdrop/pull/79

**Comment by Postlagerkarte** [comment]
closing coz fixed by #79  - thx @koryphaee !
