### ISSUE TITLE
Doesn’t work with touch screen

### ISSUE THREAD

**Issue by VladislavAntonyuk** [Postlagerkarte/blazor-dragdrop#87]

**Comment by ViRuSTriNiTy** [comment]
Most likely not true. Did you follow the polyfill hint mentioned in the readme?

**Comment by VladislavAntonyuk** [comment]
I tried the demo page from readme

**Comment by ViRuSTriNiTy** [comment]
Yeah, the demo page doesn't include the polyfill ;)
