### ISSUE TITLE
Accessing OrderPosition in OnDrop

### ISSUE THREAD

**Issue by americanslon** [Postlagerkarte/blazor-dragdrop#9]
How can I access order position in OnDrop?

Maybe something like 
`<Draggable Context="phases" Tag='new { Id = item.Id, Index = phases.OrderPosition }' OnDrop="OnDrop" >`  
That doesn't compile though as at that time there is no knowledge that `phases` is the context.

Alternatively, maybe my whole approach is wrong. What's the recommended strategy of updating and underlying list as the items get reordered?

**Comment by Postlagerkarte** [comment]
Hi @americanslon,  you are right the context is not accessible within the DraggableTag - it is only passed to the descendants of the draggable tag - this is due to Blazor RenderFragments.

However, upgrade to v1.1.3 and try this:

 `<Draggable OnDrop="(d,i)=>OnDrop(d,i)" Tag="new { Id= 42, Index = 0 }">`

```
    public void OnDrop(dynamic d, int orderPosition)
    {
        d.Index = orderPosition;
    }
```

Or you could update it inline:

 ` <Draggable OnDrop="(d,i) => d.Index = i" Tag="new { Id= 42, Index = 0 }">`

**Comment by americanslon** [comment]
Awesome thank you, that works. I'd think it's be useful to add `prevOrderPostion` so `OnDrop` as well.

AND/OR

Maybe consider making the component take a list as a parameter and modifying that underline list as things get dragged around.

**Comment by americanslon** [comment]
Hey this obviously stopped working since 'OnDrop' now takes `DraggableItem` only. 
How does my `OnDrop` handler know the order position in this new way?

**Comment by Postlagerkarte** [comment]
Hi! 

DraggableItem has a property OrderPosition:

```
        /// <summary>
        /// Order position of this draggable inside the dropzone.
        /// </summary>
        public int OrderPosition
```

You tried that?

**Comment by americanslon** [comment]
Ah yes there it is, not sure where I was looking. Thank you!
How do I now get the object of my type out of the `DraggableItem`. `(MyType)x` where x is `DraggableItem` gives a compiler error.

**Comment by Postlagerkarte** [comment]
The Tag property contains the data you have assigned:

```
         /// <summary>
        /// Gets or sets the dynamic data which belongs to this draggable.
        /// </summary>
        public dynamic Tag { get; set; }
```

**Comment by americanslon** [comment]
Thank you!

**Comment by tomesendam** [comment]
Getting the order/index of an item no longer seems to be possible using this method. Are there new methods to do this in 2.0?
