### ISSUE TITLE
[REQ] Ability to get back modified list

### ISSUE THREAD

**Issue by DoomerDGR8** [Postlagerkarte/blazor-dragdrop#91]
Is it possible to retrieve modified (sorted) list from the control? I tired to print out the list that I supply for the `Items` parameter but that list doesn't get modified.

**Comment by xavimiranda** [comment]
You can accomplish this for now by creating a reference to the DropZone and the accessing its Items property
```csharp
<DropZone @ref="dropzone" Items="MyList">
    @context.Title
</DropZone>
<button @onclick="GetSortedList">Get Sorted List</button>

@code {
    DropZone<Todo> dropzone; 
    
    void GetSortedList()
    {
        List<Todo> SortedList = dropzone.Items; //this is the sorted list
    }
}
```
